# Generated by Django 6.0.2 on 2026-02-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_contactmessage_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='twitter_url',
        ),
    ]
